add_test([=[PerfomanceTests.Test1]=]  [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database/Test]==] [==[--gtest_filter=PerfomanceTests.Test1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PerfomanceTests.Test1]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QueryTests.Test1]=]  [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database/Test]==] [==[--gtest_filter=QueryTests.Test1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QueryTests.Test1]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QueryTests.Test2]=]  [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database/Test]==] [==[--gtest_filter=QueryTests.Test2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QueryTests.Test2]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QueryTests.Test3]=]  [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database/Test]==] [==[--gtest_filter=QueryTests.Test3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QueryTests.Test3]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QueryTests.Test4]=]  [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database/Test]==] [==[--gtest_filter=QueryTests.Test4]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QueryTests.Test4]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QueryTests.Test5]=]  [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database/Test]==] [==[--gtest_filter=QueryTests.Test5]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QueryTests.Test5]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QueryTests.Test6]=]  [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database/Test]==] [==[--gtest_filter=QueryTests.Test6]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QueryTests.Test6]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/danpo/OneDrive/Рабочий стол/working db/Database]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  Test_TESTS PerfomanceTests.Test1 QueryTests.Test1 QueryTests.Test2 QueryTests.Test3 QueryTests.Test4 QueryTests.Test5 QueryTests.Test6)
